### PR TITLE
feat: update to 5.15.10

### PR DESCRIPTION
**Pull request by sanjayankur31**
Related to Fedora PR, and should be kept in sync with:  https://src.fedoraproject.org/rpms/qt5-qtwebengine/pull-request/12

### CODE REVIEW

**Comment by kwizart** [comment]
Thanks for the PR, but you may need to take-over the maintenance of the package in rpmfusion as none really maintain it in rpmfusion since keving left the package...

Would you volunteer ? Feel free to drop by #rpmfusion so we can hand-over the package.

**Comment by sanjayankur31** [comment]
Hi @kwizart , sure---I'm helping out Rex and Kevin here (see the Fedora PR where Rex has replied). I'll double-check with them and happily help with co-maintainership if they're happy with that (FAS: `ankursinha`).

**Comment by kwizart** [comment]
Ok, You should have access now... ! Please push via rfpkg and build.

Thanks !

**Comment by sanjayankur31** [comment]
Thanks very much. Will do.

**Pull request merged**
